# Numpy

## Numpy Arrays

Numpy arrays are similar to lists, but have a few key differences. 

Features of numpy arrays:
- Can be multi-dimensional
- Can only have one data type, which is typically numbers
- Ideal for doing math, plotting, and statistics
- Has a fixed size once created, but values are modifiable

In [34]:
# Import the numpy package!
import numpy as np

A Python list can be converted to a numpy array.

In [35]:
# A basic python list
fib_list = [1, 1, 2, 3, 5, 8]
# Convert list to numpy array
fib_array = np.array(fib_list)

In [36]:
print(fib_list)
print(fib_array)

[1, 1, 2, 3, 5, 8]
[1 1 2 3 5 8]


## Math in Numpy

Various math functions are available for numpy arrays.

In [37]:
# Calculating mean of numpy array
mean = np.mean(fib_array)
mean

np.float64(3.3333333333333335)

In [38]:
# Calculating maximum value of numpy array
max = np.max(fib_array)
max

np.int64(8)

In [39]:
# Calculating minimum value of numpy array
min = np.min(fib_array)
min

np.int64(1)

More Numpy mathematical functions can be found here: https://numpy.org/doc/stable/reference/routines.math.html

You can also perform math expressions with all array elements with numpy, which isn't possible with lists.

In [40]:
fib_array + 2

array([ 3,  3,  4,  5,  7, 10])

## Multi-dimensional Arrays

A numpy array can have another array within it, which makes it **multi-dimensional**.

In [12]:
multid_array = np.array([[1,2,3,4,5]])
multid_array

array([[1, 2, 3, 4, 5]])

A common type of numpy array is a two-dimensional array.

In [13]:
twod_array = np.array([[0,1,2,3,4], [5,6,7,8,9]])
twod_array

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

You can determine the dimensions, or **shape**, of an array with `np.shape()`. The output of the function looks something like this: `(2, 3)`. The first value, `2`, stands for the number of rows, while the second value, `3`, stands for the number of columns, if you were to visualize the array as a table.

In [41]:
# This array has two rows and five columns
np.shape(twod_array)

(2, 5)

There needs to be the same number of columns in each row, so an array like `np.array([[0,1,2,3], [4,5,6,7,8]])` would return an error, because there is a mismatched number of columns.

## Array Slicing

Arrays can be sliced independently according to Cartesian coordinates.

In [42]:
twod_array[0:2, 1:3]

array([[1, 2],
       [6, 7]])

The number of values sliced in each row must be equal among all rows, so if one row slices less values than another, then the lower number of values would be sliced.

For example, if one row slices all values while another slices just two, then only two values would be extracted from each row.

In [43]:
# An example of this
twod_array[:, 1:3]

array([[1, 2],
       [6, 7]])

You can also slice every other value, like with normal lists.

In [44]:
# Slicing every other value
twod_array[:, 0::2]

array([[0, 2, 4],
       [5, 7, 9]])

## Different Ways to Create an Array

There are various other ways to create an array and assign certain values to it.

In [45]:
# Makes an array filled with 0s
zeros = np.zeros(5)
print(zeros)
# Makes an array filled with 1s
ones = np.ones(5)
print(ones)
# Makes an empty array
empty = np.empty(5)

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]


You can be more specific with the array shape you want. Using `(2,4,6)` would make a two-dimensional array with four rows and 6 columns, while `(1,5)` would make a one-dimensional array with 5 entries.

In [ ]:
# A two-dimensional array with four rows and six columns
np.zeros((2,4,6))

array([[[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]]])

In [48]:
# A one-dimensional array with five entries
np.ones((1,5))

array([[1., 1., 1., 1., 1.]])

## Specifying Axis in Arrays

When an array is multi-dimensional, you need to specify the **axis** when doing certain math functions. The axis determines if you do math across rows or across columns.
- `axis = 0`: Math is done across the rows, resulting in one value for each column
- `axis = 1`: Math is done across the columns, resulting in one value for each row

In [49]:
# Example array
axis_array = np.array([[5,5,5,5,5], [3,3,3,3,3]])
# Taking an average across rows
row_average = np.mean(axis_array, axis = 0)
print(row_average)
# Taking an average across columns
column_average = np.mean(axis_array, axis = 1)
print(column_average)

[4. 4. 4. 4. 4.]
[5. 3.]
