## Week 2

### Data types:

In [ ]:
my_string = 'string'
my_int = 7
my_float = 7.0
my_list = [7, "petal", "sepal", 5.8]

print(type(my_string))
print(type(my_int))
print(type(my_float))
print(type(my_list))


<class 'str'>
<class 'int'>
<class 'float'>
<class 'list'>


### Numpy arrays:

In [ ]:
import numpy as np
array = np.array([1,1,2,3,5,8])
print(array)
print(type(array))

[1 1 2 3 5 8]
<class 'numpy.ndarray'>


You can apply operations across an array:

In [ ]:
print(array + 1)

[2 2 3 4 6 9]


### Indexing:

Use square brackets [ ] after a list or array name to indicate which value in the list or array you want to indicate:

In [ ]:
array[0]

1

In [ ]:
array_2D = np.array([[1,1,2,3,5,8],[4,6,6,1,9,8]])
array_2D[1,4]

9

In [ ]:
my_list[2]

'sepal'

Use negatives to index off the end of the list or array:

In [ ]:
array[-1]

8

### Slicing:
Use a colon `[x:y]` to indicate "from x up to but not including y"
Use two colons `[x:y:z]` to indicate "from x up to but not including y, counting by z"
Omit the x and/or y values to indicate the beginning or end:
- `[:y]` = "from the beginning up to but not including y"
- `[x:]` = "from x to the end"
- `[:]` = "the whole thing"
- `[::-1]` = "the whole thing in reverse (counting by -1)"


In [ ]:
import numpy as np
array = np.array([1,1,2,3,5,8])
array_slice = array[1:5]
print(array_slice)
print(array[0:6:2]) # prints every other value
print(array[::-1]) # prints the array in reverse

[1 2 3 5]
[1 2 5]
[8 5 3 2 1 1]


2D arrays are sliced just as you'd indicate a Cartesian position with (x,y)


In [ ]:
import numpy as np
array_2D = np.array([[1,1,2,3,5,8],[4,6,6,1,9,8]])
print("ex1:", array_2D[1,2:5]) # Row [1], Columns [2:5]
print("ex2:", array_2D[:,:2]) # All rows, the first two columns

ex1: [6 1 9]
ex2: [[1 1]
 [4 6]]
